# Observability Lab - Zabbix Agent
# Valores dinâmicos abaixo são ajustados pelo entrypoint com variáveis de ambiente.

PidFile=/var/run/zabbix/zabbix_agentd.pid
LogType=console
DebugLevel=3

Server=zabbix-server
ServerActive=zabbix-server:10051
Hostname=rocky-node-target

ListenPort=10050
ListenIP=0.0.0.0

Include=/etc/zabbix/zabbix_agentd.d/*.conf

# Permite UserParameters nas próximas partes do lab.
UnsafeUserParameters=1
